name: Gm3u8
on:
  gollum
jobs:
  downloading:
    runs-on: ubuntu-latest
    steps:
    - name: Clone your repo
      env:
        REPO: ${{ secrets.REPO }}
      run: |
        git clone https://github.com/Borber/$REPO.git

    - name: Prepare your video
      run: |
        mkdir download
        git clone "https://github.com/${GITHUB_REPOSITORY}.wiki.git"
        wiki=`echo $echo $GITHUB_REPOSITORY | cut -d "/" -f 2`.wiki
        cd "$wiki"
        drive=`git log --pretty=format: -1 --name-only *.md`
        export drive
        cd ..
        wget -q `cat $wiki/$drive | xargs` --directory-prefix=download

    - name: Install ffmpeg
      run: |
        sudo add-apt-repository ppa:jonathonf/ffmpeg-4 &> /dev/null
        sudo apt install ffmpeg &> /dev/null

    - name: Slice your file
      env:
        REPO: ${{ secrets.REPO }}
      run: |
        file=$(ls download | awk -F "/" '{print $NF}')
        name=$(echo $file | awk -F "." '{print $1}')
        mkdir $REPO/$name
        ffmpeg -i download/$file -c:v libx264 -c:a aac -strict -2 -f hls -hls_list_size 0 $REPO/$name/$name.m3u8

    - name: Upload your file
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: Borber/${{ secrets.REPO }}
          publish_branch: master
          force_orphan: true
          publish_dir: ${{ secrets.REPO }}
          commit_message: $(ls download | awk -F "/" '{print $NF}')



