name: Gm3u8
on:
  gollum
jobs:
  downloading:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare your video
      run: |
        mkdir download
        git clone "https://github.com/${GITHUB_REPOSITORY}.wiki.git"
        wiki=`echo $echo $GITHUB_REPOSITORY | cut -d "/" -f 2`.wiki
        cd "$wiki"
        drive=`git log --pretty=format: -1 --name-only *.md`
        export drive
        cd ..
        wget -q `cat $wiki/$drive | xargs` --directory-prefix=download
    - name: Install ffmpeg
      run: |
        sudo add-apt-repository ppa:jonathonf/ffmpeg-4 &> /dev/null
        sudo apt install ffmpeg &> /dev/null
        ffmpeg -version
    - name: Slice your file
      run: |
        file=$(ls download | awk -F "/" '{print $NF}')
        name=$(echo $file | awk -F "." '{print $1}')
        mkdir $name
        ffmpeg -i download/$file -c:v libx264 -c:a aac -strict -2 -f hls -hls_list_size 0 ./$name/$name.m3u8
        ls ./$name

